# version: '3.8'

# services:
#   web:
#     build: .
#     ports:
#       - "8080:80"
#     volumes:
#       - .:/var/www/html
#     restart: always


services:
  app:
    build: .
    image: lab-connect
    container_name: lab-connect
    restart: always
    expose:
      - "8002"  # Aplikasi tetap berjalan di port 8002
    networks:
      - app_network

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    restart: always
    ports:
      - "80:80"    # Untuk HTTP
      - "443:443"  # Untuk HTTPS
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt/live:/etc/letsencrypt/live:ro 
    depends_on:
      - app
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
